on: [push]

jobs:
  build:
    runs-on: centos
    steps:
    - uses: actions/checkout@v2
    - name: docker login
     env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - name: docker build tomcat-server
      run: |
        docker build -t tomcat-server
    - name: pushing Docker image to hub.docker.com
      run: |
        docker push tomcat-server
